### PR TITLE
Paper prototype

### PR DESCRIPTION
**Pull request by gilesni**
all the files are in and ready

### CODE REVIEW

**Comment by Brenisec** [comment]
The design files were not set in the same orientation. Should be fixed for better readability.

**Comment by gilesni** [comment]
I can't change the orientation for I already took the picture is it a big deal?

**Comment by Brenisec** [comment]
Ok. That's alright. The next step would be to change the name to give them some more description without opening them first.

**Comment by gilesni** [comment]
That I can do, let me work on it now

**Comment by gilesni** [comment]
I have finished renaming all the files, merge if you think it is ready

**Comment by Brenisec** [comment]
will do

**Pull request merged**
